// Base
private _brief = ["Briefing", [[],[],[],["U_B_BDU_2acr",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],[],[],"cap_patrel_dcu","G_Shades_tactical",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];
private _briefSl = ["Briefing Rangers", [[],[],[],["U_B_RBU_DCU",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],[],[],"H_Cap_usblack","G_Shades_tactical",[],["ItemMap","","","ItemCompass","ACE_Altimeter",""]]];

// Infanterie
private _infCdg = ["[INFANTERIE] Chef de groupe", [["rhs_weap_m4a1","","rhsusf_acc_anpeq15_bk_top","rhsusf_acc_ACOG_USMC",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],"rhsusf_acc_kac_grip"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["U_B_BDU_2acr",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["m81_iba2_rcr_pl_gp",[["ACRE_PRC343",1],["SmokeShellBlue",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellRed",1,1],["rhsusf_mag_15Rnd_9x19_FMJ",1,15],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],["oliv_camelbak_weistpack",[["ACRE_PRC117F",1]]],"H_MichB_dcu_G","G_Shades_tactical",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","Simc_PVS7_mount"]]];
private _infMedic = ["[INFANTERIE] Médecin", [["rhs_weap_m4_carryhandle_grip3","","rhsusf_acc_anpeq15side_bk","",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],"rhsusf_acc_kac_grip"],[],[],["U_B_BDU_2acr",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["m81_iba2_medic",[["SmokeShellBlue",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellRed",1,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30]]],["dcu_med_bag",[["ACE_splint",10],["ACE_epinephrine",10],["ACE_morphine",14],["ACE_elasticBandage",20],["ACE_packingBandage",20],["ACE_bodyBag",2],["ACE_salineIV",4],["ACE_salineIV_250",8],["ACE_salineIV_500",8],["ACE_surgicalKit",1],["ACRE_PRC343_ID_1",1]]],"H_MichB_DCU_net","G_Shades_tactical",[],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ItemWatch","Simc_PVS7_mount"]]];
private _infGenieEOD = ["[INFANTERIE] EOD", [["rhs_weap_m4a1","","rhsusf_acc_anpeq15_bk_top","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],["ACE_VMH3","","","",[],[],""],["U_B_BDU_2acr",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["m81_iba2_a_var_2",[["SmokeShellBlue",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellRed",1,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30]]],["dcu_camelbak_weistpack",[["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_EntrenchingTool",1],["ACE_DefusalKit",1],["ACE_Clacker",1],["ACRE_PRC343_ID_1",1],["rhsusf_m112_mag",5,1]]],"H_MichB_dcu","G_Shades_tactical",[],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ItemWatch","Simc_PVS7_mount"]]];
private _infRifleman = ["[INFANTERIE] Fusilier", [["rhs_weap_m4a1","","rhsusf_acc_anpeq15_bk_top","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["U_B_BDU_2acr",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["m81_iba2_flc_rflm",[["SmokeShellBlue",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellRed",1,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30]]],[],"H_MichB_dcu_G","G_Shades_tactical",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","Simc_PVS7_mount"]]];
private _infGl = ["[INFANTERIE] Grenadier", [["rhs_weap_m4_m203","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],["rhs_mag_M433_HEDP",1],""],[],[],["U_B_BDU_2acr",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["m81_iba2_grnd",[["SmokeShellBlue",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellRed",1,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30]]],["dcu_camelbak_weistpack",[["ACE_40mm_Flare_ir",2,1],["rhs_mag_M433_HEDP",13,1],["rhs_mag_m714_White",6,1],["rhs_mag_m713_Red",2,1]]],"H_MichB_dcu","G_Shades_tactical",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","Simc_PVS7_mount"]]];
private _infMg = ["[INFANTERIE] Mitrailleur", [["rhs_weap_m249_pip_ris","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ELCAN",["rhsusf_200Rnd_556x45_box",200],[],"rhsusf_acc_saw_bipod"],[],[],["U_B_BDU_2acr",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["m81_iba2_mg",[["SmokeShellBlue",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellRed",1,1],["rhsusf_200rnd_556x45_mixed_box",1,200]]],["B_patrelPack_m81",[["rhsusf_200rnd_556x45_mixed_box",1,200]]],"H_MichB_dcu","G_Shades_tactical",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","Simc_PVS7_mount"]]];
private _infMarksman = ["[INFANTERIE] Marksman", [["rhs_weap_m14_rail_d","","","rhsusf_acc_M8541_low_d",["rhsusf_20Rnd_762x51_m80_Mag",20],[],"rhsusf_acc_harris_swivel"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["U_B_BDU_2acr",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["m81_iba2_rcr_tl_gp",[["ACRE_PRC343",1],["SmokeShellBlue",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellRed",1,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhsusf_20Rnd_762x51_m118_special_Mag",4,20]]],["B_AssaultPack_rgr_05",[["ACE_Kestrel4500",1],["ACE_EntrenchingTool",1],["ACE_RangeCard",1],["rhsusf_20Rnd_762x51_m118_special_Mag",6,20]]],"H_MichB_DCU_net","G_Shades_tactical",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","Simc_PVS7_mount"]]];

// Rangers
private _sfLead = ["[RANGERS] Chef d'équipe", [["rhs_weap_m4a1","","rhsusf_acc_anpeq15_light","rhsusf_acc_eotech_552",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],"rhsusf_acc_grip3"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["U_B_RBU_DCU",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["V_Ciras2",[["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["rhsusf_mag_7x45acp_MHP",2,7],["rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30]]],["B_AssaultPack_rgr_05",[["ACRE_PRC148",1],["ACRE_PRC117F",1]]],"H_Mich_tan_W2","G_Shades_tactical",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_14"]]];
private _sfMedic = ["[RANGERS] Médic", [["rhs_weap_m4a1_d","","rhsusf_acc_anpeq15_light","rhsusf_acc_eotech_552_d",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],"rhsusf_acc_tdstubby_tan"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["U_B_RBU_DCU",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["V_Ciras",[["ACRE_PRC148",1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["rhsusf_mag_7x45acp_MHP",2,7],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],["oliv_med_bag",[["ACE_splint",10],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_packingBandage",20],["ACE_elasticBandage",20],["ACE_tourniquet",2],["ACE_salineIV",6],["ACE_salineIV_250",8],["ACE_salineIV_500",8],["ACE_surgicalKit",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",2]]],"H_Mich_tan_W2_ir","G_Shades_tactical",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_14"]]];
private _sfLmg = ["[RANGERS] Mitrailleur léger", [["rhs_weap_m249_pip_S_para","","rhsusf_acc_anpeq15side","rhsusf_acc_ELCAN",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_grip4_bipod"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["U_B_RBU_DCU",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACRE_PRC148",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",1,1],["ACE_Chemlight_HiRed",1,1],["ACE_Chemlight_HiGreen",1,1]]],["rhsusf_mbav_mg",[["SmokeShellBlue",1,1],["HandGrenade",2,1],["rhsusf_mag_7x45acp_MHP",2,7],["rhsusf_200Rnd_556x45_soft_pouch_coyote",1,200],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",2,100]]],[],"H_Mich_tan_W3_M_G","G_Shades_tactical",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_14"]]];
private _sfTp = ["[RANGERS] TP", [["rhs_weap_sr25_d","rhsusf_acc_SR25S_d","rhsusf_acc_anpeq15side","rhsusf_acc_M8541_d",["rhsusf_20Rnd_762x51_SR25_m118_special_Mag",20],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["U_B_RBU_DCU",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["V_Ciras3",[["ACRE_PRC148",1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["rhsusf_mag_7x45acp_MHP",2,7],["rhsusf_20Rnd_762x51_SR25_m993_Mag",5,20]]],["B_AssaultPack_rgr_05",[["rhsusf_acc_premier_anpvs27",1],["ACE_Kestrel4500",1],["ACE_EntrenchingTool",1],["ACE_RangeCard",1],["rhsusf_20Rnd_762x51_SR25_m993_Mag",5,20]]],"H_Mich_tan_W2_ir","G_Shades_tactical",["ACE_Vector","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_14"]]];
private _sfGl = ["[RANGERS] Grenadier", [["rhs_weap_m4a1_m203","","rhsusf_acc_anpeq15side","rhsusf_acc_eotech_552",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],["rhs_mag_M433_HEDP",1],"rhsusf_acc_grip_m203_blk"],[],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["U_B_RBU_DCU",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["rhsusf_mbav_grenadier",[["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["rhsusf_mag_7x45acp_MHP",2,7],["rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30]]],["tacpac_tan",[["ACRE_PRC148",1],["rhs_mag_M433_HEDP",13,1],["rhs_mag_m714_White",6,1],["rhs_mag_m713_Red",4,1],["ACE_40mm_Flare_ir",2,1]]],"H_Mich_tan_W3_M_G","G_Shades_tactical",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_14"]]];
private _sfEod = ["[RANGERS] EOD", [["rhs_weap_m4a1_d","","rhsusf_acc_anpeq15_light","rhsusf_acc_eotech_552_d",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],"rhsusf_acc_tdstubby_tan"],[],["ACE_VMH3","","","",[],[],""],["U_B_RBU_DCU",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["V_Ciras2",[["ACRE_PRC148",1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30]]],["dcu_hawg2",[["ACE_SpraypaintBlue",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_DefusalKit",1],["ACE_Clacker",1],["ToolKit",1],["ACE_EntrenchingTool",1],["rhsusf_m112_mag",6,1]]],"H_Mich_tan_W2_ir","G_Shades_tactical",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_14"]]];
private _sfOperator = ["[RANGERS] Opérateur", [["rhs_weap_m4a1_d","","rhsusf_acc_anpeq15_light","rhsusf_acc_eotech_552_d",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],"rhsusf_acc_rvg_de"],[],[],["U_B_RBU_DCU",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["V_Ciras3",[["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30]]],[],"H_Mich_tan_W2_ir","G_Shades_tactical",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_14"]]];

// Recos
private _reconTeamLeader = ["[RECO] Chef d'équipe", [["rhs_weap_m4a1_m203s_d","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq15side","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],["rhs_mag_M433_HEDP",1],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["Smock_WDL_3CD",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_IR_Strobe_Item",1],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_MapTools",1],["ACRE_PRC148",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["SmokeShellBlue",1,1]]],["rhsusf_mbav_grenadier",[["HandGrenade",2,1],["SmokeShell",4,1],["rhsusf_mag_15Rnd_9x19_FMJ",1,15],["rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30],["rhs_mag_m713_Red",1,1],["rhs_mag_m714_White",4,1],["ACE_40mm_Flare_ir",1,1]]],["rhsusf_assault_eagleaiii_coy",[["ACRE_PRC117F",1],["rhs_mag_M433_HEDP",9,1]]],"rhsusf_protech_helmet_rhino_ess","",["rhsusf_bino_lerca_1200_tan","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","Simc_PVS14_mount"]]];
private _reconMedic = ["[RECO] Médic", [["rhs_weap_m4a1_d","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq15_light","rhsusf_acc_ACOG_d",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],"rhsusf_acc_tdstubby_tan"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["Smock_DN_3CD",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_IR_Strobe_Item",1],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_MapTools",1],["ACRE_PRC148",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["SmokeShellBlue",1,1]]],["rhsusf_mbav_rifleman",[["HandGrenade",2,1],["SmokeShell",4,1],["rhsusf_mag_15Rnd_9x19_FMJ",1,15],["rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30]]],["rhsusf_assault_eagleaiii_coy",[["ACE_surgicalKit",1],["ACE_salineIV",6],["ACE_salineIV_250",8],["ACE_salineIV_500",8],["ACE_EntrenchingTool",1],["ACE_packingBandage",20],["ACE_elasticBandage",20],["ACE_morphine",14],["ACE_epinephrine",10],["ACE_splint",10]]],"rhsusf_protech_helmet_rhino_ess","",[],["ItemMap","","","ItemCompass","ItemWatch","Simc_PVS14_mount"]]];
private _reconSniper = ["[RECO] TE", [["rhs_weap_m24sws_d","rhsusf_acc_m24_silencer_d","","rhsusf_acc_LEUPOLDMK4_d",["rhsusf_5Rnd_762x51_m118_special_Mag",5],[],"rhsusf_acc_harris_swivel"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["Smock_3CD_3CD",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_IR_Strobe_Item",1],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_MapTools",1],["ACRE_PRC148",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["SmokeShellBlue",1,1]]],["rhsusf_mbav_mg",[["HandGrenade",2,1],["SmokeShell",4,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhsusf_5Rnd_762x51_m993_Mag",16,5]]],["oliv_camelbak_weistpack",[["ACE_Kestrel4500",1],["ACE_Tripod",1],["ACE_RangeCard",1]]],"rhsusf_protech_helmet_rhino_ess","",[],["ItemMap","","","ItemCompass","ItemWatch","Simc_PVS14_mount"]]];
private _reconMarksman = ["[RECO] Marksman", [["rhs_weap_sr25_d","rhsusf_acc_SR25S_d","rhsusf_acc_anpeq15side","rhsusf_acc_M8541_d",["rhsusf_20Rnd_762x51_SR25_m118_special_Mag",20],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["Smock_3CD_WDL",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_IR_Strobe_Item",1],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_MapTools",1],["ACRE_PRC148",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["SmokeShellBlue",1,1]]],["rhsusf_mbav_mg",[["HandGrenade",2,1],["SmokeShell",4,1],["rhsusf_mag_15Rnd_9x19_FMJ",4,15],["rhsusf_20Rnd_762x51_SR25_m118_special_Mag",6,20]]],["oliv_camelbak2_buttpack",[["ACE_Kestrel4500",1],["ACE_EntrenchingTool",1],["ACE_RangeCard",1],["rhsusf_acc_premier_anpvs27",1],["rhsusf_20Rnd_762x51_SR25_m118_special_Mag",4,20]]],"rhsusf_protech_helmet_rhino_ess","",[],["ItemMap","","","ItemCompass","ItemWatch","Simc_PVS14_mount"]]];

// Tanks
private _tankCrewman = ["[BLINDÉS] Crewman", [["rhs_weap_m4a1","","","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["U_B_BDU_2acr",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["m81_iba2_a_var_3",[["SmokeShellBlue",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellRed",1,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",4,30]]],[],"cvc_mc_g","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];

// Helo
private _rafHeloPilot = ["[HELO] Pilote hélico", [["rhs_weap_m4a1","","","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["nomex_desert",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1]]],["Airchew_vest_NH",[["SmokeShellBlue",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellRed",1,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_M855A1_Stanag",4,30]]],[],"rhsusf_hgu56p","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","Simc_PVS7"]]];

{
	_x params ["_name", "_loadout"];
	[_name, _loadout] call ace_arsenal_fnc_addDefaultLoadout;
} forEach [
	_brief,
	_briefSl,
	_infCdg,
	_infMedic,
	_infGenieEOD,
	_infRifleman,
	_infGl,
	_infMg,
	_infMarksman,
	_sfLead,
	_sfMedic,
	_sfLmg,
	_sfTp,
	_sfGl,
	_sfEod,
	_sfOperator,
	_reconTeamLeader,
	_reconMedic,
	_reconSniper,
	_reconMarksman,
	_tankCrewman,
	_rafHeloPilot
];