// Base
private _brief = ["Briefing", [[],[],[],["amf_uniform_03_CE_2",[]],[],[],"AMF_BERET_INFANTERIE","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];
private _briefFs = ["Briefing RPIMa", [[],[],[],["amf_uniform_03_MTP_2",[]],[],[],"AMF_BERET_RPIMa","G_Bandanna_oli",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];
private _briefFs = ["Briefing ALAT", [[],[],[],["amf_uniform_04_ce_2",[]],[],[],"AMF_BERET_ALAT_OR","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];

// Infanterie
private _infCdg = ["[INFANTERIE] Chef de groupe", [["AMF_614_long_01_F","","OFrP_pointer_PIRAT_EL9B","AMF_Aimpoint_CompM5",["AMF_Stanag_556x45_30Rnd_Mag",30],[],"amf_acc_614_grip3"],[],["AMF_Glock_17_TAN","","","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_01_CE_OD",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_Chemlight_IR",1,1]]],["amf_SMB_LEADER_TDF",[["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["AMF_GR_DEFF1",1,1],["AMF_GR_OFF1",1,1],["SmokeShell",4,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["AMF_Stanag_556x45_30Rnd_Mag",7,30]]],["AMF_FELIN_BACKPACK_LIGHT_TDF",[["ACRE_ER314",1],["ACRE_ER328",1],["AMF_Stanag_556x45_30Rnd_Mag",3,30],["B_IR_Grenade",1,1]]],"AMF_FELIN_L03_CE","",["R3F_JIM_LR","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ItemWatch","OFrP_Lucie"]]];
private _infMedic = ["[INFANTERIE] Médecin", [["AMF_Samas_F1_01_F","","amf_acc_laserpirat","",["AMF_FAMAS_556x45_25Rnd_Mag",25],[],"amf_acc_famas_grip3"],[],["R3F_PAMAS","","","",["R3F_15Rnd_9x19_PAMAS",15],[],""],["amf_uniform_01_CE_OD",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_Chemlight_IR",1,1]]],["amf_SMB_AUXSAN_FAMAS_TDF",[["AMF_GR_OFF1",1,1],["AMF_GR_DEFF1",1,1],["SmokeShell",4,1],["SmokeShellBlue",2,1],["AMF_FAMAS_556x45_25Rnd_Mag",8,25]]],["AMF_FELIN_BACKPACK_MEDIC_TDF",[["ACE_splint",8],["ACE_epinephrine",8],["ACE_morphine",14],["ACE_packingBandage",20],["ACE_elasticBandage",20],["ACE_tourniquet",2],["ACE_bodyBag",4],["ACE_quikclot",10],["ACE_EntrenchingTool",1],["ACE_salineIV",6],["ACE_salineIV_250",10],["ACE_salineIV_500",10],["ACE_surgicalKit",1],["AMF_FAMAS_556x45_25Rnd_Mag",2,25],["R3F_15Rnd_9x19_PAMAS",2,15]]],"AMF_FELIN_03_CE","",[],["ItemMap","","","ItemCompass","ItemWatch","OFrP_Lucie"]]];
private _infGenieEOD = ["[INFANTERIE] EOD", [["AMF_Samas_F1_01_F","","amf_acc_laserpirat","AMF_Aimpoint_CompM",["AMF_FAMAS_556x45_25Rnd_Mag",25],[],"amf_acc_famas_grip3"],[],[],["amf_uniform_01_CE_OD",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_Chemlight_IR",1,1]]],["amf_SMB_GRE_FAMAS_TDF",[["SmokeShell",4,1],["AMF_GR_DEFF1",1,1],["AMF_GR_OFF1",1,1],["AMF_FAMAS_556x45_25Rnd_Mag",9,25]]],["AMF_FELIN_BACKPACK_LIGHT_TDF",[["ACE_Clacker",1],["ACE_DefusalKit",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_EntrenchingTool",1],["ToolKit",1],["rhsusf_m112x4_mag",1,1],["rhsusf_m112_mag",4,1]]],"AMF_FELIN_03_CE","",[],["ItemMap","","","ItemCompass","ItemWatch","OFrP_Lucie"]]];
private _infRifleman = ["[INFANTERIE] Fusilier", [["AMF_Samas_FELIN_01_F","","","AMF_Eotech_552",["AMF_FAMAS_556x45_25Rnd_Mag",25],[],""],[],[],["amf_uniform_01_CE_OD",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_Chemlight_IR",1,1]]],["amf_SMB_FUS_FAMAS_TDF",[["SmokeShell",4,1],["AMF_GR_OFF1",1,1],["AMF_GR_DEFF1",1,1],["AMF_FAMAS_556x45_25Rnd_Mag",9,25]]],[],"AMF_FELIN_03_CE","",[],["ItemMap","","","ItemCompass","ItemWatch","OFrP_Lucie"]]];
private _infGl = ["[INFANTERIE] Grenadier (FAMAS)", [["AMF_Samas_FELIN_01_F","","","AMF_Eotech_552",["AMF_FAMAS_556x45_25Rnd_Mag",25],["AMF_RFG_APAV40",1],""],[],[],["amf_uniform_01_CE_OD",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_Chemlight_IR",1,1]]],["amf_SMB_GRE_FAMAS_TDF",[["SmokeShell",4,1],["AMF_GR_DEFF1",1,1],["AMF_GR_OFF1",1,1],["AMF_FAMAS_556x45_25Rnd_Mag",9,25]]],["amf_tecpack_30L",[["AMF_RFG_APAV40",14,1],["AMF_RFG_AC58",6,1]]],"AMF_FELIN_03_CE","",[],["ItemMap","","","ItemCompass","ItemWatch","OFrP_Lucie"]]];
private _infGl2 = ["[INFANTERIE] Grenadier (HK416)", [["OFrP_HK416F_C_HK269","","OFrP_pointer_PIRAT_EL9A","AMF_Aimpoint_CompM5",["OFrP_HK_30Rnd_556x45",30],["rhs_mag_M441_HE",1],""],[],["AMF_Glock_17_TAN","","","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_01_CE_OD",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_Chemlight_IR",1,1]]],["amf_SMB_GRE_TDF",[["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["AMF_GR_DEFF1",1,1],["AMF_GR_OFF1",1,1],["SmokeShell",4,1],["rhs_mag_30Rnd_556x45_M855A1_Stanag",9,30]]],["amf_tecpack_30L",[["rhs_mag_M441_HE",13,1],["rhs_mag_m713_Red",4,1],["rhs_mag_m714_White",6,1]]],"AMF_FELIN_03_CE","",[],["ItemMap","","","ItemCompass","ItemWatch","OFrP_Lucie"]]];
private _infMg = ["[INFANTERIE] Mitrailleur", [["amf_mini_mg_01_f","","","AMF_Scrome_J4",["AMF_Minimi_556x45_150Rnd_Mag",150],[],""],[],["AMF_Glock_17_TAN","","","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_01_CE_OD",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_Chemlight_IR",1,1]]],["amf_SMB_ART_TDF",[["SmokeShell",2,1],["AMF_GR_DEFF1",1,1],["AMF_Minimi_556x45_150Rnd_Mag",3,150]]],[],"AMF_FELIN_03_CE","",[],["ItemMap","","","ItemCompass","ItemWatch","OFrP_Lucie"]]];
private _infMarksman = ["[INFANTERIE] TP", [["R3F_SCAR_H_PR_20pcs_TAN","","","AMF_schmidt_benderx4_tan",["R3F_20Rnd_762x51_SCAR",20],[],"sps_atlas_bipod_m_blk"],[],["AMF_Glock_17_TAN","","","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_01_CE_OD",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_RangeCard",1],["ACE_Chemlight_IR",1,1]]],["amf_SMB_TP_SCAR_TDF",[["R3F_OB50",1],["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["SmokeShell",2,1],["AMF_GR_OFF1",1,1],["AMF_GR_DEFF1",1,1],["R3F_20Rnd_762x51_SCAR",10,20]]],[],"AMF_FELIN_03_CE","",["ACE_Yardage450","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","OFrP_Lucie"]]];
private _infEryx = ["[INFANTERIE] Tireur ERYX", [["AMF_Samas_VALO_01_F","","","AMF_Eotech_552",["AMF_FAMAS_556x45_25Rnd_Mag",25],[],"amf_acc_famas_grip5"],["AMF_Eryx","","","",["Eryx_HEAT",1],[],""],[],["amf_uniform_01_CE_OD",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_Chemlight_IR",1,1]]],["amf_SMB_FUS_FAMAS_TDF",[["SmokeShell",4,1],["AMF_GR_DEFF1",1,1],["AMF_GR_OFF1",1,1],["AMF_FAMAS_556x45_25Rnd_Mag",9,25]]],["AMF_FELIN_BACKPACK_LIGHT_TDF",[["Eryx_HEAT",1,1]]],"AMF_FELIN_03_CE","",[],["ItemMap","","ItemRadio","","ItemWatch","OFrP_Lucie"]]];

// RPIMa
private _sfLead = ["[RPIMa] Chef d'équipe", [["AMF_614_short_FS_BLK","AMF_ROTEX_V","rhsusf_acc_anpeq15side_bk","SPS_EOTech_Black_3xMAG_up",["AMF_Stanag_556x45_30Rnd_Mag",30],[],"amf_acc_614_grip5"],[],["AMF_Glock_17","","acc_flashlight_pistol","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_ER328",1],["ACE_Chemlight_IR",1,1]]],["amf_DCS_05_TAN",[["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["AMF_Stanag_556x45_30Rnd_Mag",6,30]]],["AMF_rush24_01_TAN",[["ACRE_ER323",1],["AMF_Stanag_556x45_30Rnd_Mag",4,30]]],"AMF_OPSCORE_TAN2","G_Bandanna_oli",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sfMedic = ["[RPIMa] Médic", [["AMF_614_short_fs2_tan","muzzle_snds_Shield_FDE_M","rhsusf_acc_anpeq15side","SPS_EOTech_Black_3xMAG_up",["AMF_Stanag_556x45_30Rnd_Mag",30],[],"amf_acc_614_grip7"],[],["AMF_Glock_17_BLK","","acc_flashlight_pistol","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_ER328",1],["ACE_Chemlight_IR",1,1]]],["amf_DCS_04_TAN",[["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["AMF_Glock_17_9x19_17Rnd_Mag",2,17],["AMF_Stanag_556x45_30Rnd_Mag",6,30]]],["AMF_rush24_01_TAN",[["ACE_splint",8],["ACE_epinephrine",8],["ACE_morphine",12],["ACE_packingBandage",20],["ACE_elasticBandage",20],["ACE_tourniquet",2],["ACE_bodyBag",2],["ACE_EntrenchingTool",1],["ACE_salineIV",6],["ACE_salineIV_250",10],["ACE_salineIV_500",10],["ACE_surgicalKit",1],["ACE_quikclot",10],["AMF_Stanag_556x45_30Rnd_Mag",4,30]]],"AMF_OPSCORE_TAN2","G_Bandanna_oli",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sfLmg = ["[RPIMa] Mitrailleur léger", [["R3F_Minimi_556_TAN_MK3","","rhsusf_acc_anpeq15side","rhsusf_acc_su230a_c",["R3F_MINIMI_200Rnd_556x45",200],[],""],[],["AMF_Glock_17_BLK","","acc_flashlight_pistol","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_ER328",1],["ACE_Chemlight_IR",1,1]]],["amf_JPC_03_OD",[["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["AMF_Glock_17_9x19_17Rnd_Mag",2,17],["R3F_MINIMI_200Rnd_556x45",2,200]]],["AMF_rush24_01",[["R3F_MINIMI_200Rnd_556x45",2,200]]],"AMF_OPSCORE_TAN2","G_Bandanna_oli",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sfTp = ["[RPIMa] TP", [["R3F_SCAR_H_CAM","R3F_SILENCIEUX_SCAR_H_PR","rhsusf_acc_anpeq15side","SPS_SnB_shortdot_r",["R3F_20Rnd_762x51_SCAR",20],[],"sps_atlas_bipod_m_blk"],[],["AMF_Glock_17_BLK","","acc_flashlight_pistol","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_ER328",1],["ACE_Chemlight_IR",1,1]]],["amf_DCS_03_TAN",[["ACE_RangeCard",1],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["R3F_20Rnd_762x51_SCAR",9,20]]],["AMF_rush24_01_TAN",[["ACE_Tripod",1],["ACE_EntrenchingTool",1],["R3F_20Rnd_762x51_SCAR",2,20]]],"AMF_OPSCORE_TAN2","G_Bandanna_oli",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sfGl = ["[RPIMa] Grenadier", [["rhs_weap_hk416d10_m320","muzzle_snds_Shield_black_M","rhsusf_acc_anpeq15side","sps_aimpoint_T1_3xMAG_up_Black",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan",30],["rhs_mag_M441_HE",1],""],[],["AMF_Glock_17_BLK","","acc_flashlight_pistol","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_ER328",1],["ACE_Chemlight_IR",1,1]]],["amf_DCS_04_MTP",[["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30]]],["AMF_rush24_01_MTP",[["rhs_mag_M441_HE",14,1],["rhs_mag_m713_Red",4,1],["rhs_mag_m714_White",8,1],["ACE_40mm_Flare_ir",4,1]]],"AMF_OPSCORE_TAN2","G_Bandanna_oli",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sfEod = ["[RPIMa] EOD", [["AMF_614_long_FS4_BLK","AMF_ROTEX_III","rhsusf_acc_anpeq15side_bk","sps_aimpoint_T1_3xMAG_up_Black",["AMF_Stanag_556x45_30Rnd_Mag",30],[],"amf_acc_614_grip5"],[],["AMF_Glock_17_BLK","","acc_flashlight_pistol","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_ER328",1],["ACE_Chemlight_IR",1,1]]],["amf_DCS_05_TAN",[["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["AMF_Stanag_556x45_30Rnd_Mag",6,30]]],["AMF_rush24_01_TAN",[["ACE_DefusalKit",1],["ACE_Clacker",1],["ACE_SpraypaintRed",1],["ACE_SpraypaintGreen",1],["AMF_Stanag_556x45_30Rnd_Mag",4,30],["rhsusf_m112x4_mag",1,1],["rhsusf_m112_mag",4,1]]],"AMF_OPSCORE_TAN2","G_Bandanna_oli",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sfOperator = ["[RPIMa] Opérateur", [["AMF_614_long_FS_BLK","AMF_ROTEX_III","rhsusf_acc_anpeq15side_bk","SPS_EOTech_Black_3xMAG_up",["AMF_Stanag_556x45_30Rnd_Mag",30],[],"amf_acc_614_grip5"],[],["AMF_Glock_17_BLK","","acc_flashlight_pistol","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_ER328",1],["ACE_Chemlight_IR",1,1]]],["amf_DCS_05_TAN",[["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30]]],[],"AMF_OPSCORE_TAN2","G_Bandanna_oli",[],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];

// Recos
private _sfDiver = ["[RPIMa] Plongeur", [["amf_sig552","AMF_ROTEX_V","AMF_AN_PEQ_15_black","SPS_EOTech_Black",["AMF_Sig552_556x45_30Rnd_Mag",30],[],"amf_acc_sig552_grip3"],[],["R3F_HKUSP_CE","muzzle_snds_L","R3F_LAMPE_SURB","",["R3F_15Rnd_9x19_HKUSP",15],[],""],["R3F_uniform_diver_MFO",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_MapTools",1],["ACE_CableTie",1]]],["V_RebreatherIA",[]],["R3F_sac_lourd_noir",[["ACRE_ER328",1],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["AMF_Sig552_556x45_30Rnd_Mag",10,30],["B_IR_Grenade",1,1],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellBlue",1,1],["R3F_15Rnd_9x19_HKUSP",4,15]]],"AMF_TC800_GRN_EARPROT_OD","G_B_Diving",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Wide_Green"]]];
private _sfSniper = ["[RECO] Sniper", [["amf_perseis_ii_poly_02_F","","","R3F_J10_MILDOT_DES",["AMF_Perseis_II_127x99_7Rnd_Mag",7],[],""],[],["AMF_Glock_17_BLK","","acc_flashlight_pistol","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["R3F_uniform_GhillieFULL_MFO",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_MapTools",1],["ACE_CableTie",1]]],["amf_DCS_03_OD",[["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["AMF_Perseis_II_127x99_7Rnd_Mag",4,7]]],["OFrP_Bag_CrusaderIII",[["SPS_PVS24LR",1],["ACE_Flashlight_MX991",1],["ACE_Kestrel4500",1],["ACE_EntrenchingTool",1],["ACRE_ER328",1],["ACE_RangeCard",1],["AMF_Perseis_II_127x99_7Rnd_Mag",1,7]]],"","G_Bandanna_oli",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];
private _sfSpotter = ["[RECO] Spotter", [["AMF_714_Long_01_F","rhsusf_acc_aac_762sdn6_silencer","rhsusf_acc_anpeq15side_bk","SPS_EOTech_Vudu_Black",["AMF_714_762x51_20Rnd_Mag",20],[],"bipod_01_F_blk"],[],["AMF_Glock_17_BLK","","acc_flashlight_pistol","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["R3F_uniform_GhillieFULL_MFO",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_IR_Strobe_Item",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["amf_DCS_05_RG",[["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["AMF_714_762x51_20Rnd_Mag",9,20]]],["OFrP_Bag_CrusaderIII",[["ACRE_ER328",1],["ACE_Flashlight_MX991",1],["ACE_RangeCard",1],["ACE_Kestrel4500",1],["SPS_PVS24LR",1],["ACRE_ER323",1],["SmokeShell",4,1],["AMF_GR_DEFF1",1,1],["AMF_GR_OFF1",1,1],["ACE_Chemlight_IR",2,1],["AMF_714_762x51_20Rnd_Mag",1,20],["AMF_Perseis_II_127x99_7Rnd_Mag",2,7]]],"","G_Bandanna_oli",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];

// Tanks
private _tankCrewman = ["[BLINDÉS] Équipage", [["AMF_614_short_01_F","","OFrP_pointer_PIRAT_EL9B","AMF_Aimpoint_CompM5",["AMF_Stanag_556x45_30Rnd_Mag",30],[],"amf_acc_614_grip3"],[],["AMF_Glock_17_TAN","","","",["AMF_Glock_17_9x19_17Rnd_Mag",17],[],""],["amf_uniform_01_CE_OD",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_Chemlight_IR",1,1]]],["amf_SMB_FUS_TDF",[["AMF_Glock_17_9x19_17Rnd_Mag",1,17],["AMF_GR_DEFF1",1,1],["AMF_GR_FUMF5",1,1],["SmokeShell",4,1],["AMF_Stanag_556x45_30Rnd_Mag",7,30]]],["amf_tecpack_30L",[["ToolKit",1]]],"AMF_ELNO_DH_586","amf_balaclava_goggles_od",[],["ItemMap","","","ItemCompass","ItemWatch",""]]];

// Helo
private _rafHeloPilot = ["[ALAT] Pilote hélico", [["R3F_MP7A2","","R3F_POINTEUR_SURB","AMF_AIMPOINT_MICRO_T2",["R3F_40Rnd_460x30",40],[],""],[],["AMF_Pamas","","","",["AMF_Pamas_9x19_15Rnd_Mag",15],[],""],["amf_uniform_04_ce_2",[["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",3],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_Chemlight_IR",1,1]]],["OFrP_Vest_CIRAS_Rifleman_MJK",[["AMF_GR_DEFF1",1,1],["AMF_GR_FUMF5",1,1],["SmokeShell",4,1],["AMF_Pamas_9x19_15Rnd_Mag",1,15],["R3F_40Rnd_460x30",6,40]]],["amf_tecpack_30L",[["ToolKit",1]]],"AMF_ALPHA900","",[],["ItemMap","","","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]];

{
	_x params ["_name", "_loadout"];
	[_name, _loadout] call ace_arsenal_fnc_addDefaultLoadout;
} forEach [
	_brief,
	_briefFs,
	_briefFs,
	_infCdg,
	_infMedic,
	_infGenieEOD,
	_infRifleman,
	_infGl,
	_infGl2,
	_infMg,
	_infMarksman,
	_infEryx,
	_sfLead,
	_sfMedic,
	_sfLmg,
	_sfTp,
	_sfGl,
	_sfEod,
	_sfOperator,
	_sfDiver,
	_sfSniper,
	_sfSpotter,
	_tankCrewman,
	_rafHeloPilot
];